### ISSUE TITLE
/suggestion get-top, filter by suggestion category (and title regex?)

### ISSUE THREAD

**Issue by LercDsgn** [scratchaddons-community/scradd#113]
## More options for /suggestion get-top
![image](https://user-images.githubusercontent.com/75680333/175769840-1ec8d2a9-4fa1-417a-bf27-ffcda00c70ec.png)

#### Benefits

- More customization
- Better end-user experince
- Complementing an existing feature
- Accesibility
- Helping devs find suggestions they want (which is mostly the purpose of suggesting)

------

*: could be filter too, using a system like `/addon`, forgot the name of the lib
*: RegEx search would be done by surrounding it with forward slashes `/......(optional flags here)/` ([idea by CST](https://github.com/scratchaddons-community/scradd/issues/113#issuecomment-1163528507))

------
- [X] No existing issue for this. Agree to [Code of Conduct](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CODE_OF_CONDUCT.md) & [Contributing Guidelines](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CONTRIBUTING.md)

**Comment by CST1229** [comment]
I think `title` should be a simple text search, with regex search done by surrounding the query with / (with optional flags at the end)

**Comment by RedGuy12** [comment]
categories are being removed bc ppl don’t use them correctly

**Comment by LercDsgn** [comment]
> categories are being removed bc ppl don’t use them correctly

I almost always put "new feature" because I'm not sure whether the suggestion itself is enough to make a brand new addon, even if it is different from any addon.

Maybe the categories could be split into two:

- minor feature
- major feature
-----
- extending an existing addon
- unrelated to any existing addon
- settings addition

**Comment by LercDsgn** [comment]
> I think `title` should be a simple text search, with regex search done by surrounding the query with / (with optional flags at the end).
Makes sense, I think that's how it works in js too, right?

**Comment by RedGuy12** [comment]
for title search, just use discord search

**Comment by LercDsgn** [comment]
> for title search, just use discord search

right, maybe for regex?

**Comment by LercDsgn** [comment]
also maybe start-time, end-time filters? (and/or sort-by new/old?)

**Comment by LercDsgn** [comment]
i didnt see its closed already lol

**Comment by LercDsgn** [comment]
> for title search, just use discord search

what about time filters (start-date, end-date)?

**Comment by CST1229** [comment]
> > for title search, just use discord search
> 
> what about time filters (start-date, end-date)?

Discord has after: and before: filters, too.
