### ISSUE TITLE
Suggestions rewrite

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#116]
`/suggest` command will trigger a modal to open. The modal will have "title", "description", and "image" fields. "image" will be optional while the other two will be required. Submitting the modal will create a suggestion. It will send a message in the thread containing one button titled "Answer/Edit". It will pin the button and delete the pin message. When the button is pressed it will open a modal IF the user is the suggestion creator or a dev. If they are the creator, it will show "title", "description", and "image" again like in `/suggest`. If they are a dev it will (also if they are also the creator) have a select menu to answer the suggestion with. The response to that modal will be ephemeral unless they answered it, in which case it will have the current message. `/bug-report` will have similar changes and be renamed to `/report-bug`. `/suggestion get-top` will move to `/get-top-suggestions`

Modals work much smoother in Discord.JS v14 so we will wait for that. Also, I'm not even sure if modals support prefilling, images, and/or select menus yet in Discord or Discord.JS so we may have to wait longer for this.

**Comment by RedGuy12** [comment]
prefilling: yes
images: no but this isn't required
select menus: no

crud

**Comment by Aid0nModder** [comment]
Select menus in models are an upcoming feature and you could have image just require a link instead?

**Comment by RedGuy12** [comment]
forums
