### ISSUE TITLE
Migrate 20 Addons

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#118]
Migrate https://github.com/RedGuy12/20-addons to a Scradd command `/guess-addon`. Also fix this bug 

![Image](https://user-images.githubusercontent.com/61329810/176050569-c481a8bd-d03b-4191-9d78-98b61e8414ff.png)

**Comment by CST1229** [comment]
What about /botguess?

**Comment by RedGuy12** [comment]
@CST1229 I'm thinking using subcommands - `/guess-addon user` and `/guess-addon bot` to define who is guessing. Name suggestions are welcome.
