### ISSUE TITLE
/settings

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#119]
Let users change some settings related to their account:
- pings on #potatoboard
- autoreactions on/off
- #suggestions emojis
- pings when you level up

any other ideas?

**Comment by LercDsgn** [comment]
pings on xp

**Comment by RedGuy12** [comment]
> /addon compact mode

Hm not sure, this is more about not flooding the chat

**Comment by RedGuy12** [comment]
> require the = on modmail, or ask on each

found a problem with this
already on the beta, i made the success emoji autoremove after a few sec because people didn't like it staying there
but if we make the = optional ppl wont know what was sent and what wasn't
