### ISSUE TITLE
`/modmail start` always throws an error

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none does.

### Describe the bug

Using `/modmail start` works fine, except it always throws an error after you click confirm.

### To reproduce

1. Use command
2. See error

### Expected behavior

No error 

### Relevant log output

```shell
{
  "name": "DiscordAPIError",
  "message": "Unknown Message",
  "code": 10008,
  "method": "patch",
  "path": "/channels/806602307750985803/messages/1006591200784023665",
  "stack": [
    "DiscordAPIError: Unknown Message",
    "    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)",
    "    at runMicrotasks (<anonymous>)",
    "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "    at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)",
    "    at async MessageManager.edit (/app/node_modules/discord.js/src/managers/MessageManager.js:132:15)",
    "    at async InteractionCollector.<anonymous> (file:///app/common/modmail.js:251:4)"
  ],
  "httpStatus": 404,
  "requestData": {
    "json": {
      "tts": false,
      "embeds": [
        {
          "title": "Confirmation",
          "type": "rich",
          "description": "Are you sure you want to start a modmail with **<@807109998962409483>**?",
          "url": null,
          "timestamp": 0,
          "color": 5793266,
          "fields": [],
          "thumbnail": null,
          "image": null,
          "author": {
            "name": "초준",
            "icon_url": "https://cdn.discordapp.com/embed/avatars/1.png"
          },
          "footer": null
        }
      ],
      "components": [
        {
          "components": [
            {
              "custom_id": "confirm.7vlb8kx",
              "disabled": true,
              "emoji": null,
              "label": "Confirm",
              "style": 1,
              "type": 2,
              "url": null
            },
            {
              "custom_id": "cancel.7vcmunf",
              "disabled": true,
              "emoji": null,
              "label": "Cancel",
              "style": 2,
              "type": 2,
              "url": null
            }
          ],
          "type": 1
        }
      ],
      "flags": 64
    },
    "files": []
  }
}
```

### Agree to our policies

- [X] I read, understand, and agree to follow the [Code of Conduct](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CODE_OF_CONDUCT.md).
- [X] I read, understand, and agree to follow the [Contributing Guidelines](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CONTRIBUTING.md).
- [X] I am willing to submit a PR to fix this (optional).

**Comment by retronbv** [comment]
apparently this is the line that is causing it https://github.com/scratchaddons-community/scradd/blob/main/common/modmail.js#L251

**Comment by RedGuy12** [comment]
Stable uses the code on the v1.9.6 tag not main so it is caused by https://github.com/scratchaddons-community/scradd/blob/v1.9.6/common/modmail.js#L251

**Comment by RedGuy12** [comment]
:moyai: i fixed this without realizing already on main

**Comment by retronbv** [comment]
> Stable uses the code on the v1.9.6 tag not main so it is caused by [https://github.com/scratchaddons-community/scradd/blob/v1.9.6/common/modmail.js#L251](https://github.com/scratchaddons-community/scradd/blob/v1.9.6/common/modmail.js?rgh-link-date=2022-08-09T19%3A38%3A23Z#L251)

coulda told me
