### ISSUE TITLE
`generateHash` is unnecessary

### ISSUE THREAD

**Issue by cobaltt7** [scratchaddons-community/scradd#173]
We can just append `interaction.id` to the customIds.

Also `/guess-addon` doesn't verify the hash is the same, which shouldn't cause a problem because it checks the user is the same and you can only play one game at a time, but consistency is good.

**Comment by Cool-Scratcher** [comment]
who asked

**Comment by RedGuy12** [comment]
note that it now has the @deprecated jsdoc tag

**Comment by CST1229** [comment]
> note that it now has the @deprecated jsdoc tag

(if that user is reading this, that was probably an accidental ping)
