### ISSUE TITLE
/explore-potatoes shows past count of potatoes

### ISSUE THREAD

**Issue by fractioneater** [scratchaddons-community/scradd#237]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none does.

### Describe the bug

When I search for potatoed messages with /explore-potatoes, I get a lot of duplicates, because when a message gets another potato reaction, that message gets added to the results, but the old one doesn't get removed.

### To reproduce

1. /explore-potatoes user:@fractioneater (it's easier to see for users with less potatoed messages)
2. Click next a few times, and you'll see duplicate messages.

### Expected behavior

It should only show the message once, with the current potato count.

### Relevant log output

I don't see anything relevant.

### Agree to our policies

- [X] I read, understand, and agree to follow the [Code of Conduct](https://github.com/scratchaddons-community/scradd/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I read, understand, and agree to follow the [Contributing Guidelines](https://github.com/scratchaddons-community/scradd/blob/main/.github/CONTRIBUTING.md).
- [ ] I’m willing to submit a PR to fix this (optional).

**Comment by fractioneater** [comment]
Github thinks the "Agree to our policies" section has tasks in it.

**Comment by retronbv** [comment]
probably because it doesnt recognizs the optional one as actually being optional
