### ISSUE TITLE
`/suggestion answer` response

### ISSUE THREAD

**Issue by retronbv** [scratchaddons-community/scradd#32]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none does.

### Describe the feature

Make this 
![D14993A0-52B3-461C-9EBE-4C76DCEA9707](https://user-images.githubusercontent.com/49005044/152438328-fb82eb27-fba3-427b-8ffb-7e6cd16c8502.jpeg)
Into an embed

### Reasons to add this feature

I think it looks unprofessional to just be text

### Alternatives to this feature

Keep text. Still looks unprofessional 

### Agree to our policies

- [X] I read, understand, and agree to follow the [Code of Conduct](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CODE_OF_CONDUCT.md).
- [X] I read, understand, and agree to follow the [Contributing Guidelines](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CONTRIBUTING.md).
- [X] I am willing to submit a PR to fix this (optional).

**Comment by RedGuy12** [comment]
i think that'd be too bulky.

**Comment by retronbv** [comment]
> i think that'd be too bulky.

Personally i think it would be more professional

**Comment by RedGuy12** [comment]
no. it doesnt need to take up a ton of space.
