### ISSUE TITLE
support shared custom roles

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#328]
for alts

**Comment by callumjt** [comment]
wait would mods get custom roles on alts?

**Comment by RedGuy12** [comment]
> wait would mods get custom roles on alts?

anyone who qualifies will be able to get the same custom role on the alt too



> How would alts be identified for a particular user

they would have to contact mods and request the role be added to their alt as well
there's just some bugs when mods do that currently that I'll have to fix

**Comment by Platformer444** [comment]
My approach would be to make /c-r response to have two buttons with one doing the basic Role creation while the other opening a dialogue to enter the user ID of their alt or main account which would send a DM to them to verify whether the user who pressed the button is their alt or main and if they do yes then the user would get the Role and if no then the user won't

**Comment by RedGuy12** [comment]
Problem is, I wouldn't want just any two users to share a role, only ones that are actual alts
Hence why mod intervention is a good idea

on a related topic, this may mean mods should have manage roles again... they used to but it was taken away after certain people gave themselves roles they didnt qualify and created joke roles too much
tbh they should've faced demotion instead of just no more perms lmao
I don't think we'd have problems with mods making their own roles anyway since they have custom roles tho
