### ISSUE TITLE
`/explorepotatoes` back button

### ISSUE THREAD

**Issue by retronbv** [scratchaddons-community/scradd#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none does.

### Describe the feature

Add a back button to the `/explorepotatoes` command.

### Reasons to add this feature

If you are exploring the potatoes and then someone join chat and you want to show them one you already viewed, you can click the back button.

### Alternatives to this feature

Make next button loop to start? Would be dumb if there was a lot of potatoes.

### Anything else?

<img width="444" alt="396D2ED7-35C5-4ADF-A3D1-BCB92AC2AB8F" src="https://user-images.githubusercontent.com/49005044/152440323-f303f730-7917-4080-adea-cb35237bdd16.png">

### Agree to our policies

- [X] I read, understand, and agree to follow the [Code of Conduct](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CODE_OF_CONDUCT.md).
- [X] I read, understand, and agree to follow the [Contributing Guidelines](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CONTRIBUTING.md).
- [X] I am willing to submit a PR to fix this (optional).

**Comment by RedGuy12** [comment]
no loop but back button is ok

**Comment by retronbv** [comment]
> no loop but back button is ok

i said loop as alternative to back

**Comment by retronbv** [comment]
ill start working on this

**Comment by retronbv** [comment]
in progress: https://github.com/retronbv/scradd/tree/back-button
ask here for push access and ill grant it to you
