### ISSUE TITLE
put a leaderboard button in /xp rank

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#345]
jump to the user ofc

**Comment by callumjt** [comment]
I would do this if I figure out how tf buttons work in tw

**Comment by RedGuy12** [comment]
Look at basically any file to find out how to define buttons, such as https://github.com/scratchaddons-community/scradd/blob/ee8dbc29835471b4e117279a1be710843a1bf7d2/modules/threads/autoClose.ts#L177-L189
Look at the [strife documentation](https://github.com/RedGuy12/strife.js#components) to learn how to handle button presses.

For this issue, you'll need to move the code for `top` into a function. It's not that long (~50 lines) so it's currently just inside of the `switch`.  It can stay in `index.ts`. The function will take two parameters: the interaction and the optional user ID to jump to.

**Comment by callumjt** [comment]
> Look at basically any file to find out how to define buttons, such as https://github.com/scratchaddons-community/scradd/blob/ee8dbc29835471b4e117279a1be710843a1bf7d2/modules/threads/autoClose.ts#L177-L189
> 
> Look at the [strife documentation](https://github.com/RedGuy12/strife.js#components) to learn how to handle button presses.
> 
> 
> 
> For this issue, you'll need to move the code for `top` into a function. It's not that long (~50 lines) so it's currently just inside of the `switch`.  It can stay in `index.ts`. The function will take two parameters: the interaction and the optional user ID to jump to.

How would the user decide which user they want to jump to? Or would it just be the person who clicked the button

**Comment by Platformer444** [comment]
Only if I fix my scradd repo. Its messed up

**Comment by Platformer444** [comment]
Just gimme few minutes and it will be ready

**Comment by callumjt** [comment]
dam

**Comment by YandeMC** [comment]
"few minutes" *one day later*
