### ISSUE TITLE
Show how close of a match it is in /addon

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues and none does.

### Describe the feature

We can convert the ranking to a percentage and put it in the footer

### Reasons to add this feature

This feature would be good because lerc requested it

### Agree to our policies

- [X] I read, understand, and agree to follow the [Code of Conduct](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CODE_OF_CONDUCT.md).
- [X] I read, understand, and agree to follow the [Contributing Guidelines](https://github.com/scratchaddons-community/scradd/blob/issues/.github/CONTRIBUTING.md).
- [X] I am willing to submit a PR to fix this (optional).

**Comment by retronbv** [comment]
what alternative

**Comment by RedGuy12** [comment]
> what is an alternative

none
