### ISSUE TITLE
Server-side request forgery

### ISSUE THREAD

**Issue by RedGuy12** [scratchaddons-community/scradd#496]
https://github.com/scratchaddons-community/scradd/blob/739ed525961623c697df13dd05802926ff42a6ce/modules/roles/scratch.ts#L108-L110
Fixing this is as simple as calling encodeURI on the roken. This is a critical vulnerability if not fixed before release, and could allow people to trick the site into thinking they're someone else.

@callumjt @MaterArc @YandeMC @Platformer444 if someone wants something to code

**Comment by YandeMC** [comment]
roken

**Comment by callumjt** [comment]
roken
