### ISSUE TITLE
paginate broken

### ISSUE THREAD

**Issue by YandeMC** [scratchaddons-community/scradd#514]
broke xp top

**Comment by callumjt** [comment]
The red person knows

**Comment by RedGuy12** [comment]
i do appreciate issues being made, helps me to remember

**Comment by YandeMC** [comment]
do you know what broke so mabye i can fix

**Comment by RedGuy12** [comment]
> do you know what broke

no

> so mabye i can fix

sure
just follow stack trace

**Comment by YandeMC** [comment]
but that requires effort 😭

**Comment by YandeMC** [comment]
also there is to stack to follow, no error, just "the bot didnt respond" or something

**Comment by RedGuy12** [comment]
> also there is to stack to follow, no error, just "the bot didnt respond" or something

i think I'm going crazy
