### ISSUE TITLE
Laxify bad word detection on links

### ISSUE THREAD

**Issue by cobaltt7** [scratchaddons-community/scradd#756]
Extract links out of message content and check them with boundary markers on both sides and without any evasion restrictions
Some links, such as YouTube links, are often flagged incorrectly

**Comment by RedGuy12** [comment]
tenor links are also flagged incorrectly
first step: don't do evasion restrictions on links
we'll do boundary markers if the issue continues

**Comment by RedGuy12** [comment]
oh yeah one of the main issues is the youtube `&pp=` tracking param
